#!/usr/bin/env bash
# bashrc to configure and initialise bash sessions (see the bash manual 
# for details).
#
# Copyright (C) 2016 Thomas H. Muggleton
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  For more details,
# see the GNU General Public License, included in the LICENSE file in the
# root directory of this project or available at:
# http://www.gnu.org/licenses/

umask 077

# Foreground colour definitions
BLACK='\[\033[0;30m\]'
RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
BROWN='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
PURPLE='\[\033[0;35m\]'
CYAN='\[\033[0;36m\]'
LIGHT_GRAY='\[\033[0;37m\]'
DARK_GRAY='\[\033[1;30m\]'
LIGHT_RED='\[\033[1;31m\]'
LIGHT_GREEN='\[\033[1;32m\]'
YELLOW='\[\033[1;33m\]'
LIGHT_BLUE='\[\033[1;34m\]'
LIGHT_PURPLE='\[\033[1;35m\]'
LIGHT_CYAN='\[\033[1;36m\]'
WHITE='\[\033[1;37m\]'

function get_git_string {
  local git_status="$(git status --porcelain 2>&1)"

  if [[ -n $(echo "$git_status" | grep '^fatal') ]]; then
    return 1
  fi

  local modified_files=$(echo "$git_status" | grep -c '^.[MD]')
  local staged_files=$(echo "$git_status" | grep -c '^[MARDC].')
  local untracked_files=$(echo "$git_status" | grep -c '^??')

  local gs_colour=${GREEN}

  if [ $staged_files -eq 0 ]; then
    local sf=''
  else
    local sf=" $GREEN${staged_files}S"
    local gs_colour=${YELLOW}
  fi

  if [ $modified_files -eq 0 ]; then
    local mf=''
  else
    local mf=" $RED${modified_files}M"
    local gs_colour=${LIGHT_PURPLE}
  fi

  if [ $untracked_files -eq 0 ]; then
    local uf=''
  else
    local uf=" ${LIGHT_CYAN}${untracked_files}?"
    local gs_colour=${LIGHT_GRAY}
  fi

  local current_branch=$(git branch | sed -n 's/^\* \(.*\)$/\1/p')

  echo "${gs_colour}(${current_branch}${mf}${sf}${uf}${gs_colour})"
}

function prompt_command {
  local exit_code=$?
  if [ $exit_code -eq 0 ]; then
    local exit_string=${LIGHT_GREEN}${exit_code}
  else
    local exit_string=${LIGHT_RED}${exit_code}
  fi

  local git_string=$(get_git_string)

  PS1="${exit_string}\n${WHITE}\u@\h ${CYAN}\w ${git_string} ${WHITE}\n\!\$ "
}

PROMPT_COMMAND=prompt_command

# History
export HISTIGNORE=ls

# Only use vimrc in home directory, i.e. don't source global definitions
alias vim="vim -u ~/.vimrc"
export MYVIMRC=~/.vimrc

# Aliases
alias eb='vim ~/.bashrc'
alias sb='source ~/.bashrc'
alias ll='ls -Ahl'

# Source overrides and configuration specific to this local environment
if [ -f ~/.bashrc_local ]; then
  source ~/.bashrc_local
fi
