" vimrc to configure and initialise Vim (see the Vim manual for details).
"
" Copyright (C) 2016-2017 Thomas H. Muggleton
"
" This program is free software: you can redistribute it and/or modify it
" under the terms of the GNU General Public License as published by the
" Free Software Foundation, either version 3 of the License, or (at your
" option) any later version.
"
" This program is distributed in the hope that it will be useful, but
" WITHOUT ANY WARRANTY; without even the implied warranty of
" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  For more details,
" see the GNU General Public License, included in the LICENSE file in the
" root directory of this project or available at:
" http://www.gnu.org/licenses/

set nocompatible    " Use Vim defaults

" Source plugin configuration if plugin manager is present
if filereadable(glob('~/.vim/autoload/plug.vim'))
  source $HOME/.vimrc_plugins

" Add native Vim status line in the absence of airline plugin
else
  set laststatus=2
  set ruler

endif

" -------------------------
" ---- Config Settings ----
" -------------------------

" --- Interface ---
set hidden
set wildmenu
set lazyredraw
set backspace=indent,start
highlight QuickFixLine ctermbg=Yellow ctermfg=Black guibg=Yellow guifg=Black

" --- Numbering ---
" --- needs at least Vim 7.4 to work with both ---
set number
set relativenumber

" --- Highlighting ---
syntax on
set incsearch

" --- Whitespace highlighting ---
set list
set listchars=tab:>>,trail:-
highlight SpecialKey ctermfg=magenta

" --- Indentation ---
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2

" --------------------
" --- Autocommands ---
" --------------------

" --- Set indentation based on filetype ---
autocmd FileType python setlocal shiftwidth=4
autocmd FileType python setlocal tabstop=4
autocmd FileType make setlocal shiftwidth=4
autocmd FileType make setlocal tabstop=4
autocmd FileType make setlocal noexpandtab
autocmd FileType make setlocal nolist

" --- Turn on spell check for certain file types ---
autocmd FileType markdown setlocal spell spelllang=en_gb
autocmd FileType text setlocal spell spelllang=en_gb

" ----------------
" --- Mappings ---
" ----------------

" --- Use jk to exit insert or visual mode ---
" --- taken from Learn Vimscript the Hard Way, Chapter 10, by Steve Losh ---
inoremap jk <ESC>
vnoremap jk <ESC>

" --- Move between windows with CTRL-(h|j|k|l) ---
nnoremap <C-j> <C-w><C-w>
nnoremap <C-l> <C-w><C-w>
nnoremap <C-k> <C-w>W
nnoremap <C-h> <C-w>W

" --- Cycle through buffers ---
nnoremap <TAB> :bn<CR>
nnoremap <S-TAB> :bp<CR>

" --- Quick edit vimrc ---
" --- taken from Learn Vimscript the Hard Way, Chapter 07, by Steve Losh ---
nnoremap <Leader>ev :vsplit $MYVIMRC<CR>
nnoremap <Leader>sv :source $MYVIMRC<CR>

" --- Remove side-pane for copy and paste ---
" --- taken from Shawn Biddle Vim Training 2 youtube video ---
nnoremap <Leader># :set nonu norelativenumber nolist foldcolumn=0<CR>
nnoremap <Leader>~ :set number relativenumber<CR>
